// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUC1IjtFDWMIqI03yEeweyw7vCs8HOkxM',
    appId: '1:240910910108:web:2124e4073d67d374b3a359',
    messagingSenderId: '240910910108',
    projectId: 'mynotes-47d4b',
    authDomain: 'mynotes-47d4b.firebaseapp.com',
    storageBucket: 'mynotes-47d4b.appspot.com',
    measurementId: 'G-GTL9VWN0X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGMNFVX1YEr6yPBhc_DlO7CAL-QA8W5AU',
    appId: '1:240910910108:android:f7380b84a19cca3db3a359',
    messagingSenderId: '240910910108',
    projectId: 'mynotes-47d4b',
    storageBucket: 'mynotes-47d4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBal0x9NnwHq_PHt4414CmBsb6NJh6DOt8',
    appId: '1:240910910108:ios:b68299f21ca61681b3a359',
    messagingSenderId: '240910910108',
    projectId: 'mynotes-47d4b',
    storageBucket: 'mynotes-47d4b.appspot.com',
    iosClientId: '240910910108-grb613veh831sv97n45hsbosv5kmuev7.apps.googleusercontent.com',
    iosBundleId: 'com.aloha.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBal0x9NnwHq_PHt4414CmBsb6NJh6DOt8',
    appId: '1:240910910108:ios:b68299f21ca61681b3a359',
    messagingSenderId: '240910910108',
    projectId: 'mynotes-47d4b',
    storageBucket: 'mynotes-47d4b.appspot.com',
    iosClientId: '240910910108-grb613veh831sv97n45hsbosv5kmuev7.apps.googleusercontent.com',
    iosBundleId: 'com.aloha.mynotes',
  );
}
